name: node_apply
on:
  workflow_dispatch:
env:
  KUBECONFIG: ./kubeconfig.yaml
jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node
    steps:
      - uses: actions/checkout@v3
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.3.0
      - name: install kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_B64 }}" | base64 -d > kubeconfig.yaml
      - name: helmfile apply
        env:
          WITNESS_ID: ${{ secrets.WITNESS_ID }}
          WITNESS_PRIVATE_KEY: ${{ secrets.WITNESS_PRIVATE_KEY }}
        run: |
          helmfile apply
